name: Eslint & Prettier Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v3
      with:
        node-version: 18.16.0

    - name: Install dependencies
      run: make npm_ci

    - name: Build assets
      run: npm run build

    - name: Run Eslint tests
      run: make eslint

    - name: Run Prettier tests
      run: make prettier

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: eslint-report
        path: eslint-report/
        retention-days: 30
