name: Pint & Pest Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18.16.0

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer:v2
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
        coverage: xdebug

    - name: Run composer install
      run: make composer_ci

    - name: Install dependencies
      run: make npm_ci

    - name: Prepare Laravel Application
      run: |
        make init.app
        cp .env.testing .env
        php artisan key:generate
        php artisan key:generate --env=testing

    - name: Run Laravel Pint
      run: make pint OPTIONS="--test"

    - name: Build assets
      run: npm run build

    - name: Run Laravel Server
      run: php artisan serve --host=127.0.0.1 --port=8000 > /dev/null 2>&1 &

    - name: Tests
      run: make test
